<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn-Silahkan_masuk_in_register</name>
   <tag></tag>
   <elementGuidId>fcd50c8d-cae0-45c9-980b-d1e2cf389cbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonGoInTrack</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='buttonGoInTrack']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c66fe41-d5f3-4128-b06d-fe2bb8cb63f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGoInTrack</value>
      <webElementGuid>f1f6062a-a9b1-466d-b43c-287c27c3ee3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>dc94c61e-9217-4460-a6e9-5ef279863dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silahkan
                                        Masuk</value>
      <webElementGuid>a50dd674-41a1-4b13-9458-2260b319e939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonGoInTrack&quot;)</value>
      <webElementGuid>0d7f4c7c-619b-46bf-91cd-90303de08f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buttonGoInTrack']</value>
      <webElementGuid>42fcd4ec-7f80-4c0d-a697-b276d46255c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Silahkan
                                        Masuk')]</value>
      <webElementGuid>88a89621-52d7-4d25-957b-dd0463a7e45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About CODING.ID'])[1]/preceding::a[1]</value>
      <webElementGuid>66834c98-9f40-4579-9749-d3e461adc14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Map'])[1]/preceding::a[1]</value>
      <webElementGuid>644c554b-73ef-46a9-b51f-42f1ffb9d347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/login')])[5]</value>
      <webElementGuid>7e9a81cd-de4c-42d6-a47f-e77b51218094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/a</value>
      <webElementGuid>1cfbd7a1-9699-4b64-9d3c-d586c7b1c775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buttonGoInTrack' and @href = '/login' and (text() = 'Silahkan
                                        Masuk' or . = 'Silahkan
                                        Masuk')]</value>
      <webElementGuid>8231e2f6-7a74-404b-a525-ff4a0adef12c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
